server.port=8080

server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=password123
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=1
server.ssl.enabled=true


GENIUS_TOKEN=dummy-token
